### ISSUE TITLE
Neil doesn't load under 10.12

### ISSUE THREAD

**Issue by neilio** [tekezo/Seil#68]
I know this was released today, but Seil doesn't load its kernel extension under 10.12. I can't seem to get the kext to load manually as with previous updates - is there way to work around this issue for now?

**Comment by notjosh** [comment]
If it helps you, I've done a little digging. tl;dr is kext loads fine, but doesn't do anything for me (I remap caps).

```
$ sudo kextload /Library/Application\ Support/org.pqrs/Seil/Seil.10.11.signed.kext
$ kextstat | grep -v com.apple
Index Refs Address            Size       Wired      Name (Version) UUID <Linked Against>
  140    0 0xffffff7f834d4000 0x2000     0x2000     com.nvidia.CUDA (1.1.0) 5AFE550D-6361-3897-912D-897C13FF6983 <4 1>
  146    0 0xffffff7f82b0d000 0x6000     0x6000     org.pqrs.driver.Seil (12.1.0) 9420A514-D737-3FA6-B008-CDEA735BC820 <32 5 4 3 1>
```

For future reference, this is on beta 1:

```
$ system_profiler SPSoftwareDataType
Software:

    System Software Overview:

      System Version: OS X 10.12 (16A201w)
      Kernel Version: Darwin 16.0.0
      ...
```

**Comment by notjosh** [comment]
Also fwiw, seems like it's hanging onto something and refusing to terminate/unload:

```
$ sudo kextunload /Library/Application\ Support/org.pqrs/Seil/Seil.10.11.signed.kext
(kernel) Can't unload kext org.pqrs.driver.Seil; classes have instances:
(kernel)     Kext org.pqrs.driver.Seil class org_pqrs_driver_Seil has 1 instance.
Failed to unload org.pqrs.driver.Seil - (libkern/kext) kext is in use or retained (cannot unload).
```

I assume it used to terminate/unload just fine on 10.11 at least :)

It's too late at night for me to dig into this now, but I'll take a look tomorrow if you haven't had a chance!

**Comment by tekezo** [comment]
macOS 10.12 changes of the generic keyboard and mouse drivers made a great impact on Karabiner and Seil.
We should make a large changes in Karabiner and Seil architecture.
There is not a workaround for this issue.

Please wait an update of Karabiner and Seil for macOS 10.12.
(It may take a long time.)

**Comment by bosr** [comment]
Thank you teseko for the analysis and the hard work.  

Best regards!

**Comment by ariporad** [comment]
Thanks so much @tekezo!

**Comment by BjornMulder** [comment]
Is there still no way to remap caps to esc without seil?
I really depend on this mapping..
(Yes I have done the googling)

**Comment by tekezo** [comment]
@BjornMulder Unfortunately, I don't know another way. Please use OS X 10.11 for a while.

**Comment by BjornMulder** [comment]
@tekezo 
Alright, thanks for the response.

**Comment by comex** [comment]
If anyone reading this is impatient like me, I found a hacky alternative way to map keys.  This only works with AppleEmbeddedKeyboard, which is most/all of Apple's own keyboards (run `ioreg | grep AppleEmbeddedKeyboard` to see if you have one).

You need to have System Integrity Protection disabled.  I think that's sufficient these days (used to require setting the `kext-dev-mode` boot argument but that doesn't seem to be used anymore, despite still showing up in kextcache's output).

Find the IOKit personality corresponding to your keyboard, which should be in either `/System/Library/Extensions/AppleHIDKeyboard.kext/Contents/Info.plist` or `/System/Library/Extensions/AppleUSBTopCase.kext/Contents/PlugIns/AppleUSBTCKeyEventDriver.kext/Contents/Info.plist`.  Identify the right one by comparing ProductID/VendorID to your keyboard's IDs, which you can find in the System Information app under USB (builtin keyboards) or Bluetooth (I think).  You'll need to convert from hex to decimal.

You should see something like:

            <key>IOClass</key>
            <string>AppleEmbeddedKeyboard</string>
            [..more stuff..]
            <key>ProductID</key>
            <integer>601</integer>
            <key>VendorID</key>
            <integer>1452</integer>

Edit the file (you need sudo), and put in anywhere:

            <key>KeyboardUsageMap</key>
            <dict>
                <key>0x00070039</key>
                <integer>0x00070029</integer>
            </dict>

note: 7,0x39 and 7,0x29 are the HID usage codes for caps lock and escape, respectively; you can look these up.  You can remap any keys; to remap multiple entries, repeat the two lines with 0x in them.

Make sure the file is owned by user `root` and group `wheel`.  If you edited it from within sudo this should be the case, but if you copied the file or something it might not be; in that case run `sudo chown root:wheel /whatever/path/to/Info.plist`.

Run `sudo touch /System/Library/Extensions && sudo kextcache -update-volume /`.  You should see something like this (depending on which kext you modified):

    kext-dev-mode allowing invalid signature -67030 0xFFFFFFFFFFFEFA2A for kext AppleUSBTCKeyEventDriver.kext
    kext-dev-mode allowing invalid signature -67030 0xFFFFFFFFFFFEFA2A for kext AppleUSBTopCase.kext

And reboot.  If it worked, your mappings should be in effect.  If it didn’t work, it’s probably because it decided not to load the driver (in which case it uses the generic HID keyboard driver and your function keys will be broken); you can try doing the touch/kextcache/reboot sequence again.

**Comment by zeux** [comment]
@comex Thank you! Just want to confirm this works as written with SIP disabled and without any other actions required. To bind CapsLock via a shortcut, I remapped it to F13 (0x00070068) so that it's recognized as a valid key. FWIW on my MacBook the internal keyboard has a ProductID of 610 and is located in AppleUSBTopCase.kext, but I imagine this may be different between different models.

**Comment by kennonb** [comment]
@BjornMulder If you're wanting to just re-map to ESC, you could use Keyboard Maestro. Ex. http://dsh.re/b3cd6 

However, doing more of the complex setup of using it primarily as a ~F19 key and then remapping that to CMD+CTRL+SHIFT+OPT isn't possible with Keyboard Maestro. At least not that I've been able to achieve.

**Comment by vmax77** [comment]
@kennonb Does Keyboard Maestro work with Sierra then? And just to be clear, if I want to use remap Caps as F19 and use as my Alfred toggle - Keyboard Maestro would do the trick?

**Comment by kennonb** [comment]
You won't be able to remap the key in that fashion unfortunately. At least not in a way that's really responsive. You could use AppleScript to try and pass key shortcuts back to Keyboard Maestro, but I found it to cause too much of a delay in processing, so I abandoned that idea.

**Comment by BrendanThompson** [comment]
@tekezo any updates on an ETA for even a bleeding edge version of Seil :)

**Comment by paul-howard** [comment]
For any fellow Sierra beta-testers looking to emulate the Seil/Karabiner "F19" trick to remap their CapsLock key to a vim-friendly "press-for-ctrl/tap-for-escape" configuration (as outlined nicely by @brendonrapp [here](http://www.economyofeffort.com/2014/08/11/beyond-ctrl-remap-make-that-caps-lock-key-useful/)), I was able to accomplish this by simply remapping CapsLock to Ctrl in System Prefs > Keyboard > Keyboard > Modifier Keys, then applying @kennonb's Keyboard Maestro example.

I'll still be waiting with bated breath for a Sierra-compatible version of Karabiner though, so I can get my universal Vi Mode back!

**Comment by LoMiLiMiT** [comment]
@vmax77 @paul-howard This is my workaround atm with keyboard maestro: http://imgur.com/a/DhOzr
It works pretty good :) You can easily choose F19 or other F keys.

**Comment by mistadikay** [comment]
@LoMiLiMiT worked like a charm. Thanks a ton!

**Comment by nhynes** [comment]
Here's a [quick python script](https://gist.github.com/nhynes/7bcc80bbe5e005c8520abda053320519) that makes the changes as described by @comex.

Note that you will probably have to twiddle the xpath syntax a bit since I have only tested it on my own setup (macOS w/ SPI keyboard).

**Comment by priezz** [comment]
Here https://stackoverflow.com/a/16125341 are the keycodes, that can be used with comex's approach.

**Comment by sprig** [comment]
Does anyone know how to get the product IDs for @comex's approach on a macbook (late 2015)?

The built in keyboard doesn't show up under USB, nor does the microsoft sculpt keyboard. The latter shows up as "Wireless Transceiver" (and the dongle indeed is connected to a mouse as well).

Thanks in advance!

**Comment by nklmilojevic** [comment]
Has anyone been able to simulate  ctrl+alt+cmd+shift (hyper) in Sierra? I updated today and I used in combination with BetterTouchTool to launch programs with capslock and a letter (for example Capslock + S for Spotify).

Does anyone have idea how to achieve that while I'm waiting for new versions of Seil and Karabiner?

Thanks

**Comment by wxmtech** [comment]
App ain't working, and may take more time than it seems to be, so you know.

**Comment by nklmilojevic** [comment]
Yeah, I know that, but I found some kind of a workaround with Keyboard Maestro and recording the keysequence in BTT.

**Comment by asethwright** [comment]
[Karabiner Elements](https://github.com/tekezo/Karabiner-Elements) now has a build that is working for me fine on OSX 10.12. There is not a preferences pane yet so you have to modify the key via json config file. @tekezo has provided quick examples for typical mappings [here](https://github.com/tekezo/Karabiner-Elements/blob/master/usage/README.md).

**Comment by wxmtech** [comment]
Incredible, working on karabiner-elements, anything that we could do to simulate two keys when pressing one key? I did not see an example like that.

**Comment by vmax77** [comment]
@asethwright Hey, I cant seem to get Caps Lock to trigger F19 key. This is the json file I tried to use https://github.com/vmax77/Karabiner-Elements/blob/master/examples/change_caps_lock_to_f19.json. Am I doing something wrong?

**Comment by wxmtech** [comment]
no comma after “fn”?

**Comment by tseven** [comment]
Another alternative is using [Controller Mate](https://www.orderedbytes.com/controllermate/)
It is very powerful and will allow you to re-map your caps lock key.
![screen shot 2016-09-16 at 10 45 48 am](https://cloud.githubusercontent.com/assets/311287/18595738/e2d8f338-7bfa-11e6-9fe8-b5ce265f748d.png)

I'm not sure what the limitations are for the unregistered version but it doesn't seem to affect the basic usage.

**Comment by asethwright** [comment]
@wxmtech Sorry, I only successfully remapped my caps lock to escape. Maybe there is still a problem with f19 remapping.

**Comment by BjornMulder** [comment]
Karabiner elements worked great! finally getting rid of my sore pinky syndrome. remapping caps-lock to escape works great!

**Comment by LoMiLiMiT** [comment]
Does the "Hyper Key" work with the new Karabiner elements?

**Comment by talha131** [comment]
@LoMiLiMiT Nope. Until [this issue](https://github.com/tekezo/Karabiner-Elements/issues/16) fixed.

**Comment by LoMiLiMiT** [comment]
@talha131 ahhh ok damnit, tyvm. I hope the support comes soon :/ desperately waiting ^^

**Comment by jooize** [comment]
Can Karabiner Elements do Caps Lock to Control/Escape? That and Hyper is what I most desire. ♥

**Comment by wxmtech** [comment]
not to me, at least, there’s no example on hyper keys, now just swap keys.

I also love the launcher mode, damn, miss the whole suite.

**Comment by wxmtech** [comment]
I see, thought the whole suite is completed in karabiner-elements.

**Comment by andoriyu** [comment]
I don't want to sound like harsh, but could you please move discussion not related to *Seil* and this issue in question somewhere else?

**Comment by wxmtech** [comment]
@andoriyu seil is not working in sierra, and only karabiner-elements can work related to caps lock swapping, what are you talking about, where to move the discussion. Next time @ someone.

**Comment by henriquehirako** [comment]
Any update?

**Comment by steakknife** [comment]
Seil beta 12.1.0 appears to be working on Sierra.

**Comment by zeekay** [comment]
@steakknife I'd double-check that assertion. Still broken here.

**Comment by wxmtech** [comment]
newest beta still not working on second GM.

**Comment by steakknife** [comment]
@zeekay When you're right, you're right. I don't use Seil for remapping Caps Lock anymore and just use Preferences to disable it.

**Comment by jamessa** [comment]
I found my needs can be fulfill by just using Karabiner Elements and my remapped file is like this.

`
{
    "profiles": [
        {
            "name": "Default profile",
            "selected": true,
            "simple_modifications": {
                "caps_lock": "delete_or_backspace",
                "right_command": "left_control"
            }
        }
    ]
}
`

Thank you for the amazing work on Karabiner Elements. I think it's a right way to go.

**Comment by LunarRed** [comment]
So I've cobbled to together a working Hyper Key hack in MacOS 10.12 Sierra using Karabiner-Elements and Keyboard Maestro. I posted my short walkthrough here: https://www.reddit.com/r/MacOS/comments/541oiq/how_to_get_back_your_hyper_key_in_macos_1012/

Hope this helps!

**Comment by scottming** [comment]
Any update? Seil and Karabiner are more import than Siri for me. Should I have to back to OX EI or wait a few days? Could you give me a time answer? Thanks a lot, @tekezo!

**Comment by talha131** [comment]
> Should I have to back to OX EI or wait a few days?

@scottming It depends on how you used Karabiner and Seil. If you just want to map one key to other (eg: Caps Lock to Fn, Control to Command) then Karabiner-Elements is ready.

But if you are looking for things like multiple key strokes as one (eg: Ctrl+j to left down arrow, left Control to Ctrl+Alt+Shift+Cmd), or multiple profiles then Karabiner-Elements does not have these features yet.

**Comment by scottming** [comment]
@talha131 yes, I'am looking for things to make Capslock key as a Hyper key, just like that [my xml](https://gist.github.com/scottming/a9a756a9ed35467b18a4).

**Comment by LunarRed** [comment]
@scottming Try my Karabiner-Elements and Keyboard Maestro hack/alternative. It's straightforward and will cover most of the Hyper Key shortcuts in your XML: https://www.reddit.com/r/MacOS/comments/541oiq/how_to_get_back_your_hyper_key_in_macos_1012/

**Comment by diov** [comment]
For me, the problem is that I cant get the Device Vendor Id of my keyboard through EventViewer.
Also, all my config don't take effect.

**Comment by davezatch** [comment]
@LunarRed Thanks! That covers 99% of my Hyper Key usage. A real life saver :)

**Comment by LoMiLiMiT** [comment]
Does anyone know how to give one key 2 functions? Like hold Capslock does one thing and tap does another like f18 and f19 or so.

**Comment by scottming** [comment]
@LoMiLiMiT My private.xml can do that.

2016年9月26日星期一，LoMiLiMiT <notifications@github.com> 写道：

**Comment by LoMiLiMiT** [comment]
@scottming Could you maybe share it? And does it currently work under Karabiner-Elements? That would be really cool. Like having a key with 2 functions rather than having an extra key.

**Comment by scottming** [comment]
@LoMiLiMiT Sorry, I just got up. I think this [private](https://gist.github.com/scottming/a9a756a9ed35467b18a4) is what you looking for. Capslock will send Esc when key is pressed alone or as a Hyper key when not alone.

[My article](http://scottming.com/2016/01/01/remap_keyboard/) is to explain that but written by Chinese, you could see the images to  understand that.

And here are more articles:

- [A Modern Space Cadet / Steve Losh](http://stevelosh.com/blog/2012/10/a-modern-space-cadet/#modern-software)
- [A useful Caps Lock key - BrettTerpstra.com](http://brettterpstra.com/2012/12/08/a-useful-caps-lock-key/)

**Comment by wxmtech** [comment]
@scottming this is the pre Sierra era config file, the new upgraded system has issues with Karabiner and Seil. @LoMiLiMiT I suggest to wait for tekezo to release the config examples. Check this link https://github.com/tekezo/Karabiner-Elements <https://github.com/tekezo/Karabiner-Elements>.

The following is what’s going on with the next gen of karabiner(although no GUI config presented by now yet not hyper key support at this moment). Just some simple key swapping functionality with no hyper key support.

Karabiner GUI pref window can show, but it ain’t working. Seil has the problem launching for now.

**Comment by LoMiLiMiT** [comment]
@scottming tyvm scott for sharing :) Sadly i have to wait a little bit more till it works for sierra uff :/ ty @wxmtech for pointing it out. Let's hope that this awesome tool soon works again.

**Comment by arleym** [comment]
With the new MacOS keyboard drivers will it ever be possible to map capslock/F19 to multiple modifiers, or arrow keys? Or is there considerable limitation in what Karabiner Elements will be able to do compared to its predecessor on OS X?

I'm surprised how hard it's been without them! I'd hate to roll back to El Cap only to find out I was just impatient by a few days. I really appreciate what KE can do already!

**Comment by LunarRed** [comment]
@arleym Try my Karabiner-Elements and Keyboard Maestro hack/alternative. It's straightforward and will cover most of the Hyper Key shortcuts (but not special keys like arrow and tab) in your XML: https://www.reddit.com/r/MacOS/comments/541oiq/how_to_get_back_your_hyper_key_in_macos_1012/

**Comment by chenspc** [comment]
Not sure if anyone has reported on this, but I've just realised that the newest macOS Sierra (Version 10.12.1 Beta (16B2333a)) now allows you to map Caps Lock to Escape natively. That's pretty much all I needed Seil for in the first place, so the problem is sorted for me. 

I updated my system just now with my developer account, so this might not be available to the public yet. But hang in there.

**Comment by asethwright** [comment]
@chenspc I understand this isn't available yet perhaps. But for when it is, can you how did you did this?

**Comment by arleym** [comment]
@LunarRed Yes, this hack has been the only way I could get by with macOS this long! Arrows, and tab, and remapping fn key to multiple modifiers are the kinds of deal-breakery things I feel like I can't like without :) If it wasn't for that Maestro fix I'd probably be a potato farmer right now.

**Comment by asethwright** [comment]
After a quick update, you can definitely natively map caps lock to escape. This is only working on the 10.12.1 Beta as @chenspc mentioned.

System Prefs -> Keyboard -> Modifier Keys

<img width="669" alt="screen shot 2016-09-28 at 11 04 21 am" src="https://cloud.githubusercontent.com/assets/1045292/18919290/89025a32-856b-11e6-8249-4347419766c7.png">

**Comment by chenspc** [comment]
@asethwright sorry, I only just saw your previous post. I should have given a brief instruction in mine. I did exactly what you did in the System Prefs.

**Comment by sprig** [comment]
Hi Everyone,

Sorry if this is a bit offtopic, but I think this is my best chance to find a bunch of people on Sierra who may have noticed this, and hopefully this is not too offtopic:

Does anyone else suddenly have their cmd+click stop functioning as normal? For me, before the final update but during the beta it worked fine, e.g. in chrome, and I was even able to rearrange icons in the upper menu. After the update it simply stopped working. Did anyone else experience anything similar? I'm trying to figure out whether I just need to reinstall / delete some plist / whatever else, or whether it is a problem with the OS.

**Comment by arleym** [comment]
I used the Karabiner Elements + Keyboard Maestro combo for a week; great for app switching. Today I stumbled upon an alternative using Hammerspoon: http://brettterpstra.com/2016/09/29/a-better-hyper-key-hack-for-sierra/ it has some advantages like doing sequential hotkeys (e.g. Hyper+W,F to open a specific app)! I'm still trying to get the hang of the Lua stuff, but I have a feeling this combo will allow me to do everything I want.

**Comment by rtgoodwin** [comment]
@sprig Yes I have this issue too. I cmd-click almost every link when browsing (I have TooManyTabs Syndrome) and it seems to have stopped working randomly when K-E was installed. But, I don't know if it's happening elsewhere so could be a Chrome bug.

**Comment by andoriyu** [comment]
@rtgoodwin can confirm the same thing in Firefox and can't shift-select things in Airmail.

**Comment by jammi** [comment]
I have had the same issue; it's all modifier-clicks and doesn't work again until reboot.

**Comment by sprig** [comment]
Thanks for the responses guys,

@rtgoodwin one way to test is in Finder - cmd+click should select/deselect additional files rather than moving the selection. I actually suspected another app until you claimed it was related to K-E.

Now I can verify that it is caused by K-E (possibly in combination with something): If I remove the org.pqrs.karabiner.* files from /Library/LaunchDaemons and /Library/LaunchAgents and reboot, cmd+click works. When I add them back and reboot, cmd+click does not work. I'll add an issue there.

**Comment by crazybaz** [comment]
can anybody tell me what is wrong with my karabiner config?
{
    "profiles": [
        {
            "name": "Default profile",
            "selected": true,
            "simple_modifications": {
                "caps_lock": “f19”
            }
        }
    ]
}
i just wish it maps my caps_lock to f19 key, but it does't, mac os 10.12

**Comment by undefiened** [comment]
@crazybaz this config is works for me
`{
    "profiles": [
        {
            "name": "Default profile",
            "selected": true,
            "simple_modifications": {
                "caps_lock": "f19"
            }
        }
    ]
}`

In /Users/username/.karabiner.d/configuration file.

**Comment by crazybaz** [comment]
my mistake, mac replace smart quotes...
now it's ok!
thx

**Comment by aa715** [comment]
Hello guys. Please help me. 

On Mac OS Yosemite my CapsLock was changed to f19, and f19 changed to option+command+shift+control. 

On Sierra Seil don't work.

I've made change CapsLock top f19 with Karabiner Elements, but f19 to option+command+shift+control don't work(

My xml on karabiner

<?xml version="1.0"?>
<root>
<item>
    <name>Remap Caps Lock to Hyper</name>
    <appendix>OS X doesn't have a Hyper. This maps Left Control to Control + Shift + Option + Command.</appendix>
    <identifier>caps_lock_to_hyper</identifier>
    <autogen>
        --KeyToKey--
        KeyCode::F19,
        KeyCode::COMMAND_L,
        ModifierFlag::OPTION_L | ModifierFlag::SHIFT_L | ModifierFlag::CONTROL_L
    </autogen>
</item>
</root>

Thanks in advance

**Comment by sprig** [comment]
@aa715 Karabiner also doesn't work in Sierra (AFAIK - otherwise most of this discussion would be pointless).

I found the most robust solution/workaround to be the hammerspoon hack that @arleym posted, as I used hammerspoon anyway. You can use it to launch programs, move (and resize) windows around, and even directly send the hyper combination - or anything else you feel like doing, really.
The only (slight, in my opinion) issue is that you can't keep the hyper key pressed and spam other combos - you need to release hyper after each (other) keypress (though even that can be overcome, I think - it just hasn't bothered me enough to be worth the effort).

**Comment by aa715** [comment]
@sprig sorry my english very bad( I haven't up to the end understood your answer

In hammerspoon it is impossible to make so that pressing of one key replaced pressing of combo keys?

**Comment by sprig** [comment]
@aa715 possible:

e.g. you can have caps+a -> cmd+opt+ctrl+k
but unlike in Seil if you press caps+a and then caps+b, you need to release caps in between.

**Comment by nklmilojevic** [comment]
@sprig 

Can you share your Hammerspoon config?

Thanks

**Comment by sprig** [comment]
@nklmilojevic [Enjoy](https://gist.github.com/sprig/7cfb5664fc52fda8f2a88529ce94f49f)!

**Comment by mitchellnemitz** [comment]
For anyone else who is getting this error on 10.11.6, you can manually run `sudo kextload /Library/Application\ Support/org.pqrs/Seil/Seil.10.11.signed.kext` and Seil will work again. I don't know why it's not loading properly on boot in 10.11 now, but at least it still works if you force it.

**Comment by nhooyr** [comment]
@asethwright can you somehow remap escape to capslock as well?

**Comment by danielcompton** [comment]
macOS 10.12.1 is now out, and contains support for remapping Caps Lock to Esc:

<img width="445" alt="screenshot of system preferences 26-10-16 10-09-26 am" src="https://cloud.githubusercontent.com/assets/811954/19704472/4874fb64-9b64-11e6-8560-f1a271e9275a.png">

**Comment by jammi** [comment]
@danielcompton That's only because the upcoming MB(P) models don't have a physical Esc key anymore. They're replacing the entire row of keys with a touch area and fingerprint reader.

**Comment by steakknife** [comment]
@jammi Confirmed by pictures hidden in 10.12.1

**Comment by wxmtech** [comment]
/System/Library/PrivateFrameworks/PassKitUI.framework/Versions/A/Resources

 Resource location on 10.12.1

**Comment by steakknife** [comment]
That was a concept mock-up by a designer guessing into the ether, not
"leaked" subassemblies. Only a few tens of thousands of people actually
know and they're all under NDA.

**Comment by raddevon** [comment]
For those of you looking to map caps lock to ctrl and esc on Sierra, I came across a Hammerspoon config that does a pretty good job. First, map caps lock to control in Keyboard preferences. Then, use this Hammerspoon config: https://gist.github.com/arbelt/b91e1f38a0880afb316dd5b5732759f1

**Comment by clickysteve** [comment]
Anybody got suggestions for a workaround to use the Caps Lock key to trigger keycode 80, a la [this article](https://www.jamiestarke.com/2014/11/21/better-use-of-caps-lock-key/), now that Seil isn't playing nicely in Sierra?

**Comment by aa715** [comment]
Somebody will answer or not? Whether it is possible to remap caps-lock to ctrl+cmd+option+shift????

**Comment by sprig** [comment]
@aa715 I answered your question.

**Comment by aa715** [comment]
@sprig in hammerspoon ?

**Comment by sprig** [comment]
@aa715 yes, Karabiner Elements + Hammerspoon

**Comment by arleym** [comment]
I was able to get Capslock = Hyper working with a specific PR of Karabiner Elements! I followed this: https://sayzlim.net/remapping-hyper-key-macos-sierra/

**Comment by aa715** [comment]
@sprig I can't make a config for hammerspoon. How to remap in him a key to combo keys. It is possible in more detail the instruction if you doesn't complicate? 

Thanks in advance

**Comment by aa715** [comment]
@arleym thank you!! It's great!

**Comment by mcourteaux** [comment]
This can be closed. macOS finally has support for this natively. Just go to Keyboard preferences -> modifier keys, and set caps lock to escape.

![](http://i.imgur.com/CfLUVEj.png)

**Comment by sprig** [comment]
@mcourteaux you do realize that Seil is used for other things in addition remapping caps to escape?

**Comment by mcourteaux** [comment]
@sprig: True, I fixed my post.

**Comment by lindsaymarkward** [comment]
Is there a way to map Caps Lock to delete (back space) with 10.12 now?

**Comment by mitchellnemitz** [comment]
Natively through the keyboard settings panel, or you can use karabiner
elements.

On Mar 1, 2017 11:00 PM, "Lindsay Ward" <notifications@github.com> wrote:

Is there a way to map Caps Lock to delete (back space) with 10.12 now?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/tekezo/Seil/issues/68#issuecomment-283549827>, or mute
the thread

**Comment by lindsaymarkward** [comment]
Oops, I deleted my question before I saw it had been answered.
Native does not give "delete" as an option, but Karabiner Elements works well, thank you. I looked at the start and end of these comments but missed it in the middle.

**Comment by quantumproducer** [comment]
Hello, Seil still does not let me remap capslock to backspace successfully. The box in Seil 12.0 is checked. I checked my keyboard modifier keys like the instructions said. I restarted my computer. "Cannot connect to kernel extension". :(  I will switch to linux for my next computer..

**Comment by notjosh** [comment]
@quantumproducer I can definitely map caps to backspace, but (as explained in the thread!) it's by using https://github.com/tekezo/Karabiner-Elements under 10.12.x instead of Seil. Give that a shot! :)

**Comment by quantumproducer** [comment]
@notjosh I missed that, I didn't realize there was a new Elements out. It's been hard to tack with Seil, DoubleCommand and Karabiner. Thank you, this works, you are a hero!

**Comment by quantumproducer** [comment]
@notjosh since installing, I've noticed that I cannot adjust my control, alt + windows key on my Kineses frestyle keyboard. The modifier keys yin preferences seem to be ignored. I tried disabling the RControl, RCommand rebindings built into Seil (not sure why those are default), restated computer, I still cannot adjust the functionality.

**Comment by chingun** [comment]
I have this problem too and I want to delete Seil now but I cannot open the preferences to do so, and when I try to delete it manually it says seil is being used. How do I delete this?

**Comment by marlonbernardes** [comment]
Since I was only using Seil/Karabiner to remap <kbd>caps lock</kbd> ➡<kbd>F19</kbd> and F19 to `Esc (when tapping) / Ctrl (holding)` and this feature does not seem to be supported (as of this writing), this is what I ended up doing to achieve the same results without using Seil/Karabiner:

   1. close karabiner/seil if these apps are still running (optionally uninstall them)
   2. Execute the script below

```sh
# It assumes you have `homebrew` already installed.
mkdir -p ~/.hammerspoon/Spoons
git clone https://github.com/jasonrudolph/ControlEscape.spoon.git ~/.hammerspoon/Spoons/ControlEscape.spoon
cd ~/.hammerspoon/Spoons/ControlEscape.spoon
script/setup
```

3. Give accessibility access to hammerspoon (Settings -> Security and Privacy -> Privacy tab)
![image](https://user-images.githubusercontent.com/2975955/36301739-35be9b18-1306-11e8-9350-205c20244592.png)

4.  This will change the behaviour of your Ctrl (so it sends `Esc` when tapped). Now all you gotta do is to remap your Caps Lock to Ctrl (Settings -> Keyboard -> modifier keys):

![image](https://user-images.githubusercontent.com/2975955/36301822-771e5378-1306-11e8-9118-6a9855a50f75.png)
